#!/bin/bash
# generate-base-dockerfile.sh - Generate Dockerfile for MT5 base image
# Usage: ./generate-base-dockerfile.sh <snapshot_dir> [base_image] [image_tag]
#
# This script generates a Dockerfile for building the MT5 base image.
# The base image contains MT5, EA/DLL files, and profile snapshots,
# but NO credentials (credentials come from volumes at runtime).
#
# Exit Codes:
#   0 - Success
#   1 - Snapshot validation failed
#   2 - Template error
#   3 - Write failed

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Default values
DEFAULT_BASE_IMAGE="mt5-local:working"
DEFAULT_MT5_USER="kasm-user"
DEFAULT_MT5_UID="1000"
DEFAULT_MT5_GID="1002"

# Show usage
usage() {
    cat << EOF
Usage: $0 <snapshot_dir> [base_image] [image_tag]

Generate a Dockerfile for building the MT5 base image.

Arguments:
  snapshot_dir  Path to snapshot directory
  base_image   Base Docker image (default: $DEFAULT_BASE_IMAGE)
  image_tag    Tag for generated Dockerfile variable (default: mt5-base:latest)

Environment Variables:
  TERMINAL_ID   Override Terminal ID (default: auto-detect from snapshot)
  MT5_INSTALL_PATH  Override MT5 installation path (default: auto-detect)

Examples:
  $0 ./snapshot
  $0 ./snapshot gmag11/metatrader5_vnc:1.0 mt5-base:v1.0

Note:
  The generated Dockerfile does NOT include credentials.
  Credentials should be mounted from a Docker volume at runtime.

EOF
    exit 0
}

# Check arguments
if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
fi

SNAPSHOT_DIR="$1"
BASE_IMAGE="${2:-$DEFAULT_BASE_IMAGE}"
IMAGE_TAG="${3:-mt5-base:latest}"

# Discover Terminal_ID from snapshot
discover_terminal_id() {
    local snapshot_dir="$1"
    
    # Check metadata first
    if [ -f "$snapshot_dir/.metadata" ]; then
        local metadata_id
        metadata_id=$(grep "^TERMINAL_ID=" "$snapshot_dir/.metadata" 2>/dev/null | cut -d= -f2)
        if [ -n "$metadata_id" ]; then
            echo "$metadata_id"
            return 0
        fi
    fi
    
    # Find from Terminal directory
    local terminal_ids
    terminal_ids=$(find "$snapshot_dir/Terminal" -maxdepth 1 -type d -name '[A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9][A-F0-9]' 2>/dev/null)
    
    if [ -n "$terminal_ids" ]; then
        basename "$terminal_ids"
        return 0
    fi
    
    return 1
}

read_metadata_value() {
    local key="$1"
    local default_value="$2"

    if [ -f "$SNAPSHOT_DIR/.metadata" ]; then
        local value
        value=$(grep "^${key}=" "$SNAPSHOT_DIR/.metadata" 2>/dev/null | cut -d= -f2- | head -1)
        if [ -n "$value" ]; then
            echo "$value"
            return 0
        fi
    fi

    echo "$default_value"
}

sanitize_numeric_value() {
    local value="$1"
    local default_value="$2"

    if printf '%s' "$value" | grep -qE '^[0-9]+$'; then
        echo "$value"
    else
        echo "$default_value"
    fi
}

# Generate Dockerfile content
generate_dockerfile() {
    local snapshot_dir="$1"
    local base_image="$2"
    local terminal_id="$3"
    local mt5_user="$4"
    local mt5_uid="$5"
    local mt5_gid="$6"
    
    {
        printf '# Dockerfile for MT5 Base Image\n'
        printf '# Generated by generate-base-dockerfile.sh\n'
        printf '# DO NOT include credentials - credentials come from volumes at runtime\n'
        printf '\n'
        printf 'FROM %s\n' "$base_image"
        printf '\n'
        printf '# Metadata\n'
        printf 'LABEL maintainer="MT5 Docker Team"\n'
        printf 'LABEL description="MetaTrader 5 with EA/DLL pre-configured"\n'
        printf 'LABEL mt5.terminal_id="%s"\n' "$terminal_id"
        printf 'LABEL mt5.base_image="%s"\n' "$base_image"
        printf 'LABEL mt5.user="%s"\n' "$mt5_user"
        printf '\n'
        printf '# Set environment variables\n'
        printf 'ENV BASE_TERMINAL_PATH="/opt/mt5-base-terminal"\n'
        printf 'ENV CREDENTIALS_PATH="/config/credentials"\n'
        printf 'ENV MT5_USER="%s"\n' "$mt5_user"
        printf 'ENV MT5_UID="%s"\n' "$mt5_uid"
        printf 'ENV MT5_GID="%s"\n' "$mt5_gid"
        printf '\n'
        printf '# Create base terminal directory\n'
        printf 'RUN mkdir -p "/opt/mt5-base-terminal"\n'
        printf '\n'
        printf '# Fix missing lsiown command (required by s6-overlay init-adduser)\n'
        printf '# Without this, s6-overlay crashes during init-adduser phase before X11/VNC/openbox start\n'
        printf 'RUN printf '"'"'#!/bin/sh\\nexec chown "$@"\\n'"'"' > /usr/bin/lsiown \\\n'
        printf '    && chmod +x /usr/bin/lsiown\n'
        printf '\n'
        printf '# Copy FULL Terminal directory structure to base template\n'
        printf '# This preserves profiles, charts, EA/DLL attachments, etc.\n'
        printf '# Credentials will be injected at runtime\n'
        printf 'COPY Terminal/ /opt/mt5-base-terminal/Terminal/\n'
        printf '\n'
        printf '# Copy profile data to base template\n'
        printf '# MQL5/Profiles contains Charts with .chr files (including AutoTrading for EA)\n'
        printf 'COPY MQL5/ /opt/mt5-base-terminal/MQL5/\n'
        printf 'COPY Experts/ /opt/mt5-base-terminal/MQL5/Experts/\n'
        printf 'COPY Libraries/ /opt/mt5-base-terminal/MQL5/Libraries/\n'
        printf 'COPY Config/ /opt/mt5-base-terminal/Config/\n'
        printf 'COPY Profiles/ /opt/mt5-base-terminal/Profiles/\n'
        printf '# Also copy profiles/ directory for Templates and SymbolSets\n'
        printf 'COPY profiles/ /opt/mt5-base-terminal/profiles/\n'
        printf '\n'
        printf '# Fix ownership of base template so cp -a preserves correct ownership\n'
        printf 'RUN chown -R %s:%s /opt/mt5-base-terminal \\\n' "$mt5_uid" "$mt5_gid"
        printf '    && find /opt/mt5-base-terminal -type d -exec chmod 755 {} \\; \\\n'
        printf '    && find /opt/mt5-base-terminal -type f -exec chmod 644 {} \\;\n'
        printf '\n'
        printf '# Copy custom start.sh to /Metatrader/ (overwrites base start.sh)\n'
        printf 'COPY start.sh /Metatrader/start.sh\n'
        printf 'RUN chmod +x /Metatrader/start.sh \\\n'
        printf '    && chown %s:%s /Metatrader/start.sh\n' "$mt5_uid" "$mt5_gid"
        printf '\n'
        printf '# Keep the base image init flow so X11/VNC/openbox still boot correctly\n'
        printf '# /init will call /Metatrader/start.sh which handles MT5 startup\n'
        printf '# Credentials are mounted at runtime via /config/credentials\n'
    } > "$SNAPSHOT_DIR/Dockerfile"
}

# Main execution
main() {
    MT5_USER="$(read_metadata_value "REFERENCE_MT5_USER" "$DEFAULT_MT5_USER")"
    MT5_UID="$(sanitize_numeric_value "$(read_metadata_value "REFERENCE_MT5_UID" "$DEFAULT_MT5_UID")" "$DEFAULT_MT5_UID")"
    MT5_GID="$(sanitize_numeric_value "$(read_metadata_value "REFERENCE_MT5_GID" "$DEFAULT_MT5_GID")" "$DEFAULT_MT5_GID")"

    echo ""
    echo "=========================================="
    echo "  Dockerfile Generation"
    echo "=========================================="
    echo ""
    
    # Validate snapshot directory
    if [ ! -d "$SNAPSHOT_DIR" ]; then
        log_error "Snapshot directory does not exist: $SNAPSHOT_DIR"
        exit 1
    fi
    
    # Discover Terminal_ID
    local terminal_id="${TERMINAL_ID:-}"
    if [ -z "$terminal_id" ]; then
        log_info "Discovering Terminal_ID..."
        terminal_id=$(discover_terminal_id "$SNAPSHOT_DIR")
        if [ -z "$terminal_id" ]; then
            log_error "Failed to discover Terminal_ID"
            log_error "Make sure the snapshot contains the Terminal directory"
            exit 2
        fi
    fi
    log_success "Terminal_ID: $terminal_id"
    
    # Copy start.sh to snapshot directory if not present
    local start_sh_src="$SCRIPT_DIR/start.sh"
    if [ ! -f "$start_sh_src" ]; then
        log_error "start.sh not found at: $start_sh_src"
        exit 3
    fi
    
    log_info "Copying start.sh to snapshot directory..."
    cp "$start_sh_src" "$SNAPSHOT_DIR/start.sh"
    
    # Generate Dockerfile
    log_info "Generating Dockerfile..."
    
    generate_dockerfile "$SNAPSHOT_DIR" "$BASE_IMAGE" "$terminal_id" "$MT5_USER" "$MT5_UID" "$MT5_GID"
    log_success "Dockerfile generated: $SNAPSHOT_DIR/Dockerfile"
    
    echo ""
    echo "=== Dockerfile Generated ==="
    echo "  Base Image: $BASE_IMAGE"
    echo "  MT5 User: $MT5_USER (${MT5_UID}:${MT5_GID})"
    echo "  Terminal ID: $terminal_id"
    echo "  Output: $SNAPSHOT_DIR/Dockerfile"
    echo ""
    log_info "To build the image:"
    echo "  docker build -t $IMAGE_TAG $SNAPSHOT_DIR"
    echo ""
    log_info "To run with credentials:"
    echo "  docker run -v mt5-creds-{account}:/config/credentials -e TERMINAL_ID=$terminal_id $IMAGE_TAG"
    echo ""
    log_warning "Make sure start.sh exists in the snapshot directory or script directory"
}

main "$@"
